backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: src/pages/img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Suraj Jagtap"}
      - {label: "Twitter Handle", name: "twitterHandle", widget: "string", default: "surajdjagtap"}
      - {label: "Featured Image", name: "featuredImage", widget: "string"}
      - {label: "Image link", name: "imageLink" widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Keywords", name: "keywords", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
